language: node_js
node_js:
- stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules
branches: 
  only: # 指定分支提交时才会运行travis ci
    - hexo
install:
  - npm install hexo-cli -g
  - hexo init blog
  - mv blog/* . && rm -r blog
  - git clone https://github.com/theme-next/hexo-theme-next.git themes/next
script:
  - hexo generate
deploy:
  local-dir: ./public
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: hexo